apiVersion: v1
kind: ConfigMap
metadata:
  name: [[[ .Source.name ]]]
  namespace: [[[ .Source.namespace ]]]
  origin: [[[ .Source.origin ]]]
data:
  name: [[[ .Cluster.name ]]]
  platform: [[[ default "''" .Cluster.platform ]]]
  global_value: [[[ .Values.global_key ]]]
  cluster_value: [[[ .Values.cluster_key ]]]
  source_value: [[[ .Values.source_key ]]]
  keys: "[[[ keys .Values | join "," ]]]"
  cluster_inline_folded: >[[[ default "" .Values.cluster_inline_folded | nindent 4 ]]]
  cluster_inline_literal: |[[[ default "" .Values.cluster_inline_literal | nindent 4 ]]]
  cluster_inline_single_quoted: '[[[ default "" .Values.cluster_inline_single_quoted | indent 4 | trim ]]]'